name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 6 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
